name: 'Direct merge'

description: 'GitHub action which merges one branch into another'

branding:
  color: 'green'
  icon: 'git-merge'

inputs:
  owner: # owner of the repo
    description: 'Owner of the repo. Defaults to current repository owner'
    required: false

  repo: # name of the repo
    description: 'Name of the repo. Defaults to current repository'
    required: false

  source-branch: # name of source branch
    description: 'Name of the source branch (from)'
    required: true

  target-branch: # name of target branch
    description: 'Name of the target branch (to)'
    required: true

  GITHUB_TOKEN:
    description: 'Pass in secrets.GITHUB_TOKEN'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
